[package]
name = "pattern"
version = "0.1.0"
edition = "2021"

[features]
defmt = [
    "dep:defmt"
]

[dependencies]
defmt = { version = "0.3.5", optional = true }
tiny-serde = { git = "https://github.com/AdinAck/tiny-serde", branch = "main" }
